newproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('news', views.news , name="news"),
    path('news-details/<slug:slug>',views.news_details,name='news-details'),
    path('sports/', views.sports, name="sports"),

]

news/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=100, unique=True)
    slug=models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class News(models.Model):
    category=models.ForeignKey(Category, on_delete=models.PROTECT)
    title=models.CharField(max_length=100)
    slug=models.SlugField(max_length=100, unique=True)
    image=models.ImageField(upload_to='images/')
    description=models.TextField()
    date=models.DateTimeField(auto_now_add=True)
    page_views=models.IntegerField(default=0)

    def __str__(self):
        return self.title
    
    def limit_description(self):
        return self.description[:100]+'...' 

    class Meta:
        verbose_name_plural='News'

news/views.py
from django.shortcuts import render
from .models import *
from django.core.paginator import Paginator

# Create your views here.
def index(request):
    data={
        'categoryData': Category.objects.all(),
        'newsData': News.objects.all(),
    }
    return render(request, 'pages/index.html',data)

def news_details(request, slug):
    find_data = News.objects.get(slug=slug)
    cat_id = find_data.category_id
    related_news = News.objects.filter(category_id=cat_id).exclude(slug=slug)
    data = {
        'newsData':find_data,
        'relatedNews':related_news,
    }
    return render(request, 'pages/news-details.html', data)

def sports(request):
    data={
        'sports':News.objects.all().filter(category=2)
    }
    return render(request,'pages/sports.html',data)

def news(request):
    if request.method == "POST":
        search = request.POST.get('search')
        n_data = News.objects.filter(title__icontains=search)
        paginator = Paginator(n_data, 50)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        data = {
            'newsData': object
        }
        return render(request, 'pages/news.html', data)

    else:
        n_data = News.objects.all()
        paginator = Paginator(n_data, 2)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        data = {
            'newsData': page_obj,
        }
        return render(request, 'pages/news.html', data)

news/templates/layouts/footer.html
</body>
</html>

news/templates/layouts/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% comment %}
    <script src="https://cdn.tailwindcss.com"></script> {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
</head>

<body>
    <div class="container mb-5">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'sports' %}">Sports</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'news' %}">News</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Dropdown
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled">Disabled</a>
                        </li>
                    </ul>
                    <form class="d-flex" method="post" action="{% url 'news' %}" role="search">
                        {% csrf_token %}
                        <input class="form-control me-2" required name="search" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </div>

news/templates/layouts/main.html
{% include 'layouts/header.html' %}
{% block content %}
{% endblock  %}
{% include 'layouts/footer.html' %}

news/templates/pages/index.html
{% extends 'layouts/main.html' %}
{% block content %}

<div class="container">
    <div class="row">
        {% for category in categoryData %}
        <div class="col-md-12">
            <h3>
                <a href="">{{ category.name }}</a>
            </h3>

            <div class="row">
                {% for news in category.news_set.all %}
                <div class="col-md-4">
                    <div class="card">
                        {% if news.image %}
                        <img src="{{ news.image.url}}" class="card-img-top" alt="...">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="cardtitle">{{ news.title }}</h5>
                            <p class="card-text">{{ news.description }}</p>
                            <a href="{% url 'news-details' news.slug %}" class="btn btn-primary">Visit</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock  %}

news/templates/pages/news-details.html
{% extends 'layouts/main.html' %}

{% block content%}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Detail news</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <h3 class="card-title">{{newsData.title}}</h3>
            {% if newsData.image %}
            <img src="{{newsData.image.url}}" class="card-img-top" style="object-fit: cover;" alt="..."> 
            {% endif %}
            <p class="card-text">{{newsData.description}}</p>
        </div>
        {% if relatedNews %}
        <div class="col-md-4">
            <h1>Related News</h1>
            <ul>
                {% for rnews in relatedNews %}
                <li><a href="{% url 'news-details' rnews.slug %}">{{ rnews.title }}</a></li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}

news/templates/pages/news.html
{% extends 'layouts/main.html' %}
{% block content %}

<div class="container">

    <div class="row">
        {% for news in newsData %}
        <div class="col-md-3">
            <div class="card">
                {% if news.image %}
                <img src="{{ news.image.url}}" class="card-img-top" height="250px" alt="...">
                {% endif %}
                <div class="card-body">
                    <h5 class="cardtitle">{{ news.title }}</h5>
                    <p class="card-text">{{ news.limit_description }}</p>
                    <a href="{% url 'news-details' news.slug %}" class="btn btn-primary">Visit</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="pagination">
        <span class="step-links">
            {% if newsData.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ newsData.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ newsData.number }} of {{ newsData.paginator.num_pages }}.
            </span>

            {% if newsData.has_next %}
            <a href="?page={{ newsData.next_page_number }}">next</a>
            <a href="?page={{ newsData.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>



</div>



{% endblock %}

news/templates/pages/sports.html
{% extends 'layouts/main.html' %}
{% block content %}
<div class="container">
    <div class="row">

        {% for newsdata in sports %}
        <div class="col-md-4">

            <div class="card" style="width: 18rem;">

                <img src="{{newsdata.image.url}}" class="card-img-top" height="200px" width="250px"
                    alt="{{newsdata.title}}">

                <div class="card-body">
                    <h5 class="card-title">{{newsdata.title}}</h5>
                    <p class="card-text">{{newsdata.limit_description}}</p>
                    <a href="{% url 'news-details' newsdata.slug %}" class="btn btn-primary">Visit</a>
                </div>
            </div>

        </div>

        {% endfor %}
    </div>


</div>

{% endblock %}